version: 0.2

phases:
  install:
    commands:
      - curl -fsSL https://deb.nodesource.com/setup_14.x | bash - &&\
      - sudo apt install -y nodejs
      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor | tee /etc/apt/trusted.gpg.d/yarn.gpg
      - echo "deb [signed-by=/etc/apt/trusted.gpg.d/yarn.gpg] https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
      - apt install --no-install-recommends yarn
    pre_build:
      commands:
        - echo Installing dependencies...
        - yarn
    build:
      commands:
        - echo Testing...
        - yarn test
        - echo Building...
        - yarn build
artifacts:
  files: '**/*'
  discard-paths: no
  base-directory: dist
